Problem: container image build fails on arm64 for pg14-15
```
 #51 35.44 /omni/.pg/Linux-RelWithDebInfo/15.14/build/include/postgresql/server/port/atomics/arch-x86.h:143:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
 #51 35.44         register char _res = 1;
```

Solution: ensure we include cppgres.hpp prior to omni

The reason for that is that cppgres has accommodations for this issue in
the form of disabling this error when including Postgres headers.

By letting cppgres.hpp include Postgres headers first, we should be able
to avoid the issue.