Problem: GitHub Actions fails on macos-13
```
cat: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/colima.rb: No such file or directory
Error: Process completed with exit code 1.
```

Solution: upgrade to a newer GitHub action to setup Docker