Problem: A build from scratch on a Debian system gives an error due to a conflict between gettext imported from libintl for ada_url and the gettext defined in c.h in PostgreSQL's headers.
The relevant part of the error:

```
/usr/include/libintl.h:39:14: error: expected unqualified-id before ‘const’
   39 | extern char *gettext (const char *__msgid)
      |              ^~~~~~~
...
gmake[2]: *** [extensions/omni_web/CMakeFiles/omni_web.dir/build.make:121: extensions/omni_web/CMakeFiles/omni_web.dir/urlpattern.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:6951: extensions/omni_web/CMakeFiles/omni_web.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
```

Solution: Move the PostgreSQL headers to after the ada headers into the
extern C block.