Problem: omni_worker doesn't compile with Clang 17
```
boost/interprocess/segment_manager.hpp(1055,41): error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
1055 |          hdr = block_header_t::template from_first_header(reinterpret_cast<index_data_t*>((void*)((char*)buffer_ptr + front_space)));
```

Solution: apply a patch for this issue in Boost Interprocess

The issue: https://github.com/boostorg/interprocess/issues/258
The fix: https://github.com/boostorg/interprocess/commit/6fd141ab27fcb7f044745a548746b9cfe7bb0c66

This required me to add quick-and-dirty patching system for compressed
dependencies.