Problem: GitHub docs action fails again
```
ERROR: Ignored the following versions that require a different python version: 4.0.0 Requires-Python <3.12,>=3.7; 4.0.1 Requires-Python <3.12,>=3.7; 4.0.2 Requires-Python <3.12,>=3.7; 4.0.3 Requires-Python <3.12,>=3.7; 4.0.4 Requires-Python <3.12,>=3.7
ERROR: Could not find a version that satisfies the requirement mkdocs-include-markdown-plugin==4.0.4 (from versions: 0.0.1, 0.0.2, 0.1.0, 1.0.0, 2.0.0, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.3.0, 2.4.0, 2.5.0, 2.6.0, 2.6.1, 2.7.0, 2.7.1, 2.7.2, 2.8.0, 3.0.0, 3.0.1, 3.1.0, 3.1.1, 3.1.3, 3.1.4, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.3.0, 3.4.0, 3.4.1, 3.5.0, 3.5.1, 3.5.2, 3.6.0, 3.6.1, 3.7.0, 3.7.1, 3.8.0, 3.8.1, 3.9.0, 3.9.1, 5.0.0, 5.1.0, 6.0.0, 6.0.1, 6.0.2, 6.0.3)
ERROR: No matching distribution found for mkdocs-include-markdown-plugin==4.0.4

Notice:  A new release of pip is available: 23.2.1 -> 23.3.1
Notice:  To update, run: pip install --upgrade pip
Error: Process completed with exit code 1.
```

Solution: upgrade the plugin and update docs

There was a breaking change in the plugin so I had to update paths to
included files.