Problem: building docker images fails
```
error: failed to compile `cargo-pgrx v0.11.4`, intermediate artifacts can be found at `/tmp/cargo-installpit9R4`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

Caused by:
package `clap v4.5.4` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.72.0
```

Solution: pin `cargo-pgrx` version to one that works on Rust 1.72

https://github.com/tcdi/plrust/issues/410

Upgrade plrust to 1.2.8 while at it.