Problem: building Python packages fails sporadically
Error looks like this:

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/omnigres/omnigres/build/languages/python/omni_python/dist/omni_python-0.1.0.tar.gz'
```

Solution: ensure index publishing depends on the main target