Problem: omni extension upgrade in CI still fails
```
ERROR:  omni extension 0.1.0 is incompatible with a preloaded omni library of 0.1.1, please upgrade
STATEMENT:  create extension omni version '0.1.0' cascade;
```

Solution: ensure we create extension under matching omni
and upgrade with the newer one.