Problem: omni_httpc tests may fail
The error will look like this:

```yaml
query: create extension omni_httpd cascade
error: extension "omni_httpd" has no installation script nor update path for version "version"
```

Solution: ensure omni_httpc tests depend on omni_httpd
because we use it to set up a test server.

Also, since omni_httpc now requires omni_httpd for testing, and vice
versa, we have to handle this in the script that provisions dependencies
and avoid a deadlock.