Problem: docker manifest CI job fails
```
Error: Input required and not supplied: tags
```

Solution: pin the manifest action to 0.4.3

Once v1 is cut, we'll need to rename `images` key to `tags`